name: Run scheduled task

on:
  workflow_call:
    inputs:
      name:
        description: The scheduled task name
        default: Run scheduled task
        type: string
      script:
        description: The script to update
        default: |-
          yarn
          yarn update
        type: string
      message:
        description: The script to get commit message
        default: echo "Update ($(date +'%Y-%m-%d'))"
        type: string

jobs:
  keep-scheduled-workflow-activity:
    name: Keep scheduled task alive
    uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v2

  scheduled:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    env:
      UPDATE_SCRIPT: ${{ inputs.script }}
      GET_COMMIT_MESSAGE_SCRIPT: ${{ inputs.message }}
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      #  RUNNER_DEBUG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Generate scripts
        run: |-
          node --eval "fs.writeFileSync('__update.sh', process.env.UPDATE_SCRIPT, {mode: 0o777})"
          node --eval "fs.writeFileSync('__get-commit-message.sh', process.env.GET_COMMIT_MESSAGE_SCRIPT, {mode: 0o777})"

      - name: Run update script
        run: bash __update.sh

      - name: Prepare
        run: |-
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
          echo "COMMIT_MESSAGE=$(bash __get-commit-message.sh)" >> "$GITHUB_ENV"
          cat "$GITHUB_ENV"

      - name: Clean
        run: |-
          rm __update.sh __get-commit-message.sh

      - uses: peter-evans/create-pull-request@v8
        with:
          title: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          branch: automated-update-${{ env.CURRENT_DATE }}
          branch-suffix: timestamp
