name: Run scheduled task

on:
  workflow_call:
    inputs:
      script:
        description: The script to update
        default: |
          yarn
          yarn update
        type: string
      title:
        description: The script to get pull request title
        default: |
          echo "Update ($(date +'%Y-%m-%d'))"
        type: string

jobs:
  keep-scheduled-workflow-activity:
    name: Keep scheduled task alive
    uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v2

  scheduled:
    name: Run scheduled task
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      #  RUNNER_DEBUG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Run update script
        run: |
          ${{ inputs.script }}
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
          echo "PULL_REQUEST_TITLE=$(${{ inputs.title }})" >> "$GITHUB_ENV"

      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: ${{ env.PULL_REQUEST_TITLE }}
          title: ${{ env.PULL_REQUEST_TITLE }}
          branch: automated-update-${{ env.CURRENT_DATE }}
          branch-suffix: timestamp
